name: Backend Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and test backend module
        working-directory: backend
        run: mvn clean install -Dspring.profiles.active=test

      - name: Build and test persistence module
        working-directory: backend/persistence
        run: mvn clean install -Dspring.profiles.active=test

      - name: Build and test logic module
        working-directory: backend/logic
        run: mvn clean install -Dspring.profiles.active=test
